sudo: required
notifications:
  email: false
dist: trusty
language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test
before_script:
  - yarn develop > /dev/null &
  - sleep 5
after_script:
  - yarn coverage && cat coverage/lcov.info | coveralls
