sudo: required
notifications:
  email: false
dist: trusty
language: node_js
node_js:
  - '8'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn global add
  - yarn
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
before_script:
  - truffle develop &
  - sleep 5
after_script:
  - yarn coverage && cat coverage/lcov.info | coveralls
